version: '3.9'

services:
  illustry_mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - illustry_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPass
      MONGO_INITDB_DATABASE: illustry-database
    networks:
      - illustry-network

  illustry:
    image: dxworks/illustry
    restart: always
    ports:
      - "7001:7000"
    environment:
      MONGODB_CONNECTION_URI: mongodb://illustry_mongo:27017
      MONGODB_USER: root
      MONGODB_PASSWORD: rootPass
      MONGODB_DBNAME: illustry-database
    depends_on:
      - illustry_mongo
    networks:
      - illustry-network
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.illustry.entrypoints=web,web-secured
      - traefik.http.routers.illustry.rule=Host(`illustry.localhost`)
      - traefik.http.routers.illustry.service=illustry
      - traefik.http.services.illustry.loadbalancer.server.port=7000
      - traefik.docker.network=traefiknet
      - traefik.http.routers.illustry.tls=true
      - traefik.http.routers.illustry.tls.certresolver=default

volumes:
  illustry_mongo: {}
networks:
  illustry-network:
  traefiknet:
    external: true